Align installtion proceduire with ocm repo
open-component-model/ocm-website pull request #302
Opened 2024-07-29 11:43 UTC by morri-son

align installtion proceduire with ocm repo

2024-08-01 13:57 UTC, n-boshnakov requested changes

2024-08-01 13:57 UTC, n-boshnakov commented on content/docs/getting-started/installation.md
> +## Build and run it yourself
```suggestion
## Build and Run It Yourself
```

2024-08-01 13:57 UTC, n-boshnakov commented on content/docs/getting-started/installation.md
> +Install the latest release from any of
```suggestion
## Overview 

You can install the latest release of the OCM CLI from any of of the following sources (more details below):
```

2024-08-01 13:57 UTC, n-boshnakov commented on content/docs/getting-started/installation.md
> +To install with `bash` for macOS or Linux execute the following command:
```suggestion
To install with `bash` for macOS or Linux, execute the following command:
```

2024-08-01 14:06 UTC, frewilhelm requested changes

2024-08-05 15:42 UTC, frewilhelm approved these changes

2024-08-07 08:06 UTC, n-boshnakov approved these changes
/lgtm

2024-08-07 08:06 UTC, merged